/* 此规范为 uni 规范，可以按照自己的需要选择是否实现 */
import { RecordErrorCode, RecordFail } from "./interface.uts"
/**
 * 错误主题
 * 注意：错误主题一般为插件名称，每个组件不同，需要使用时请更改。
 * [可选实现]
 */
export const UniErrorSubject = 'wxz-record';


/**
 * 错误信息
 * @UniError
 * [可选实现]
 */
export const RecordErrors : Map<RecordErrorCode, string> = new Map([
  /**
   * 错误码及对应的错误信息
   */
  [9010001, '录音权限被拒绝'],
  [9010002, '录音初始化失败'],
  [9010003, '录音启动失败'],
  [9010004, '录音停止失败'],
  [9010005, '录音过程中发生错误'],
  [9010006, '参数错误'],
]);


/**
 * 错误对象实现
 */
export class RecordFailImpl extends UniError implements RecordFail {
  
  override errCode: RecordErrorCode

  /**
   * 错误对象构造函数
   */
  constructor(errCode : RecordErrorCode) {
    super();
    this.errSubject = UniErrorSubject;
    this.errCode = errCode;
    this.errMsg = RecordErrors.get(errCode) ?? "";
  }
}
